<?php
require_once __DIR__ . '/content/marketing.php';
$page_title = 'Índice — ERP + Lupita';
$page_description = marketingString('hero.text');
$home_slider = true;
$heroModules = ['hr','tasks','expenses','petty','inventory','pos','sales','receivables','kpis'];
$heroModuleRoutes = ['hr'=>'recursos-humanos','tasks'=>'procesos-tareas','expenses'=>'gastos','petty'=>'caja-chica','inventory'=>'inventarios','pos'=>'punto-de-venta','sales'=>'ventas','receivables'=>'cartera','kpis'=>'kpis'];
include 'header.php';
?>
<main id="main-content" class="mk-page">
<section class="mk-hero mk-hero-human" data-module-hero>
  <div class="module-backgrounds" aria-hidden="true"><?php foreach ($heroModules as $index => $module): ?><img class="mk-hero-photo <?= $index===0?'is-active':'' ?>" data-module-image="<?= $module ?>" src="/imgs/hero-module-<?= $module ?>-v1.jpg" width="1672" height="941" alt="" fetchpriority="<?= $index===0?'high':'low' ?>" decoding="async"><?php endforeach; ?></div>
  <div class="mk-hero-shade" aria-hidden="true"></div>
  <div class="mk-container mk-hero-grid">
  <div class="mk-hero-copy"><p class="mk-eyebrow"><span class="mk-dot" aria-hidden="true"></span><?= marketingText('hero.eyebrow') ?></p><h1><?= marketingText('hero.title') ?></h1><p class="mk-lead"><?= marketingText('hero.text') ?></p><div class="mk-actions"><a class="mk-button" href="#lupita"><?= marketingText('hero.agents.cta') ?><span aria-hidden="true">↗</span></a><a class="mk-text-link" href="/contacto.php"><?= marketingText('cta.short') ?><span aria-hidden="true">↗</span></a><div class="module-image-links"><?php foreach ($heroModules as $index => $module): ?><a data-module-link="<?= $module ?>" href="/modulo-<?= $heroModuleRoutes[$module] ?>.php" <?= $index ? 'hidden' : '' ?>><span class="module-link-action"><?= marketingText('moduleHero.view') ?></span><strong><?= marketingText('moduleHero.'.$module.'.label') ?></strong><small class="module-link-feature"><?= marketingText('moduleHero.'.$module.'.feature') ?></small><span aria-hidden="true">↗</span></a><?php endforeach; ?></div></div><p class="mk-trust"><?= marketingText('hero.trust') ?></p></div>
  <?php include __DIR__ . '/content/hero-slider.php'; ?>
</div></section>
<section class="mk-principle"><div class="mk-container"><span><?= marketingText('hero.note') ?></span><div class="mk-pillar-strip"><?php foreach(['people','processes','products','finance'] as $i=>$pillar): ?><span><i class="mk-pillar-dot mk-tone-<?= $i ?>" aria-hidden="true"></i><?= marketingText($pillar) ?></span><?php endforeach; ?></div></div></section>
<section class="mk-section"><div class="mk-container"><div class="mk-section-heading"><p class="mk-eyebrow"><?= marketingText('value.eyebrow') ?></p><h2><?= marketingText('value.title') ?></h2></div><div class="mk-value-grid"><?php foreach(['one','two','three'] as $i=>$item): ?><article><span class="mk-outline-number" aria-hidden="true">0<?= $i+1 ?></span><h3><?= marketingText('value.'.$item) ?></h3><p><?= marketingText('value.'.$item.'.text') ?></p></article><?php endforeach; ?></div></div></section>
<section class="mk-section mk-soft" id="lupita"><div class="mk-container"><div class="mk-agent-intro"><div><p class="mk-eyebrow"><?= marketingText('nav.agents') ?></p><h2><?= marketingText('lupita.title') ?></h2><p class="mk-lead"><?= marketingText('lupita.text') ?></p></div><div class="mk-lupita-identity" aria-hidden="true"><div class="mk-lupita-circle">L<span>✦</span></div><strong>Lupita</strong><div class="mk-identity-line"></div><div class="mk-identity-initials"><span>C</span><span>E</span><span>F</span><span>C</span></div></div></div>
<div class="mk-agent-grid"><?php foreach(['control'=>['Controla','C','one'],'scale'=>['Escala','E','two'],'finance'=>['Finanzas','F','three'],'corporate'=>['Corporativo','C','four']] as $key=>$agent): ?><article class="mk-agent-card"><span class="mk-specialist-mark mk-agent-<?= $key ?>" aria-hidden="true"><?= $agent[1] ?></span><h3><?= $agent[0] ?></h3><p class="mk-agent-role"><?= marketingText('agent.'.$key.'.title') ?></p><p><?= marketingText('agent.'.$key.'.text') ?></p></article><?php endforeach; ?></div><p class="mk-fine-print"><?= marketingText('agents.note') ?></p></div></section>
<section class="mk-section" id="implementacion"><div class="mk-container"><div class="mk-section-heading"><p class="mk-eyebrow"><?= marketingText('implementation.eyebrow') ?></p><h2><?= marketingText('implementation.title') ?></h2><p><?= marketingText('implementation.text') ?></p></div><?php marketingSteps(); ?></div></section>
<section class="mk-section mk-soft"><div class="mk-container mk-split"><div><p class="mk-eyebrow"><?= marketingText('feature.people') ?></p><h2><?= marketingText('plans.title') ?></h2><p class="mk-lead"><?= marketingText('plans.text') ?></p><a class="mk-button" href="/planes.php"><?= marketingText('plans.link') ?><span aria-hidden="true">↗</span></a></div><div class="mk-plan-path"><?php foreach(['control'=>'Controla','scale'=>'Escala','corporate'=>'Corporativo'] as $key=>$name): ?><a href="/planes.php#<?= $key ?>"><div><strong><?= $name ?></strong><p><?= marketingText('plan.'.$key) ?></p></div><span aria-hidden="true">↗</span></a><?php endforeach; ?></div></div></section>
<section class="mk-section"><div class="mk-container mk-learning"><span class="mk-learning-icon" aria-hidden="true">↗</span><div><h2><?= marketingText('learn.title') ?></h2><p><?= marketingText('learn.text') ?></p></div><a class="mk-text-link" href="/modo-aprendiz.php"><?= marketingText('learn.link') ?><span aria-hidden="true">→</span></a></div></section>
<?php marketingClosing(); ?>
</main>
<script src="/js/module-hero.js?v=20260922-3"></script>
<?php include 'footer.php'; ?>
